services:
  certmonitor:
    build: .
    container_name: certmonitor
    command: ["python", "src/main.py"]
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
